//////////////////////////////////////////////////////////////////////
//   Alan Oursland  
// 
//   ESP Java implementation.
//
//	 This code is a direct port of Faustino Gomez's ESP code
//   that was code started from Daniel Polani's translation of 
//   Dave Moriarty's original SANE code from C to C++.
//   
//   $Log: SignalHandler.java,v $
//////////////////////////////////////////////////////////////////////////
public class SignalHandler {
	public static boolean gInterrupt;
	public static void setUpCtrlC() {
		/*
		Registers the signal handler for the SIGINT signal which is
		generated by pressing CRTL-C.
		*/
//		signal(SIGINT, signalHandlerSIGINT );
		gInterrupt = false;
		Runtime.getRuntime().addShutdownHook(new Thread(new Runnable() {
			public void run() {
				gInterrupt = true;
				try {
					Thread.sleep(1000);
				} catch( InterruptedException e ) {
				}
			}
			}, "Shutdown call"));
	}  /* setUpCtrlC */
	
}